CREATE TABLE IF NOT EXISTS oauth_client_details (
  client_id VARCHAR(256) NOT NULL,
  resource_ids VARCHAR(256) DEFAULT NULL,
  client_secret VARCHAR(256) DEFAULT NULL,
  scope VARCHAR(256) DEFAULT NULL,
  authorized_grant_types VARCHAR(256) DEFAULT NULL,
  web_server_redirect_uri VARCHAR(256) DEFAULT NULL,
  authorities VARCHAR(256) DEFAULT NULL,
  access_token_validity INTEGER DEFAULT NULL,
  refresh_token_validity INTEGER DEFAULT NULL,
  additional_information VARCHAR(4096) DEFAULT NULL,
  autoapprove VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (client_id)
);

INSERT INTO oauth_client_details
(
    client_id, client_secret, resource_ids, scope, authorized_grant_types, web_server_redirect_uri,
    authorities, access_token_validity, refresh_token_validity, additional_information, autoapprove
)
SELECT 'client1', '$2a$10$mM8H4KS5umKaVFafx9fLFuBqYDv8y9.muL50IoO7dfQaAGngXsSEq', null, 'read,write',
       'authorization_code,password, implicit, refresh_token',
       null, 'ROLE_TRUSTED_CLIENT', 36000, 2592000, null, null
  FROM dual
 WHERE NOT EXISTS(SELECT * FROM oauth_client_details WHERE client_id = 'client1');

CREATE TABLE IF NOT EXISTS user
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_name VARCHAR(32) NOT NULL,
    password VARCHAR(100) NOT NULL,
    user_type INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,

    PRIMARY KEY (id)
);

INSERT INTO user
(
    user_name, password, user_type, created_at
)
SELECT 'user1', '$2a$10$oXhcs6qujNbFA5yXauupSuWLQpMjVbAskvPbMvcUzurpsdIuSXs7m', 2, NOW()
  FROM dual
 WHERE NOT EXISTS (SELECT * from user WHERE user_name = 'user1');

